### ISSUE TITLE
More restrictive use of the `rrule` name

### ISSUE THREAD

**Issue by yebai** [withbayes/Taped.jl#26]
At the moment, we are using `rrule` in a generic way, in the sense that they can mean both actual `rrule` for a function and the generated gradient function for a tape. It is better to keep a distinction between these two for better clarity.

**Comment by willtebbutt** [comment]
> At the moment, we are using rrule in a generic way, in the sense that they can mean both actual rrule for a function and the generated gradient function for a tape. It is better to keep a distinction between these two for better clarity.

I know we discussed this yesterday, but I'm now realising that I'm not entirely sure what you mean. Could you please elaborate?

**Comment by willtebbutt** [comment]
Ah, right. I agree regarding the location of the distribution tests.

I don't know that I follow your reasoning regarding the `unrolled_function` `rrule!!`: it is most certainly an `rrule!!`, so it _ought_ to be referred to as an `rrule!!`. It's possible that you find it confusing because the documentation is still being developed, but I don't feel that it's an abuse of terminology. On the contrary, it's is a completely correct use of terminology.

**Comment by willtebbutt** [comment]
Resolved by #34
